2011/08/03 07:48:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "controller/action".' in C:\xampp\htdocs\Yii\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(136): CWebApplication->runController('controller/acti...')
#1 C:\xampp\htdocs\Yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\getIt\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/getIt/index.php/controller/action
2011/08/03 08:12:32 [error] [exception.CException] exception 'CException' with message 'Property "Usuarios.password" is not defined.' in C:\xampp\htdocs\Yii\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(129): CComponent->__get('password')
#1 C:\xampp\htdocs\getIt\protected\models\Usuarios.php(60): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\getIt\protected\components\UserIdentity.php(43): Usuarios->validatePassword('belian')
#3 C:\xampp\htdocs\getIt\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#4 C:\xampp\htdocs\Yii\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#5 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 C:\xampp\htdocs\Yii\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#7 C:\xampp\htdocs\getIt\protected\controllers\SiteController.php(88): CModel->validate()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(277): CController->run('login')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#15 C:\xampp\htdocs\getIt\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/getIt/index.php/site/login
2011/08/03 08:12:58 [error] [exception.CException] exception 'CException' with message 'Property "Usuarios.username" is not defined.' in C:\xampp\htdocs\Yii\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(129): CComponent->__get('username')
#1 C:\xampp\htdocs\getIt\protected\components\UserIdentity.php(48): CActiveRecord->__get('username')
#2 C:\xampp\htdocs\getIt\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\Yii\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\Yii\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\getIt\protected\controllers\SiteController.php(88): CModel->validate()
#7 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#8 C:\xampp\htdocs\Yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(277): CController->run('login')
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\Yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#14 C:\xampp\htdocs\getIt\index.php(13): CApplication->run()
#15 {main} REQUEST_URI=/getIt/index.php/site/login
2011/08/03 08:41:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'getit'@'189.187.202.158' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:364
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(313): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(291): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(372): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CApplication.php(429): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(609): CApplication->getDb()
#5 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(2275): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(372): CActiveRecordMetaData->__construct(Object(Clientes))
#7 C:\xampp\htdocs\Yii\framework\web\CActiveDataProvider.php(72): CActiveRecord::model('Clientes')
#8 C:\xampp\htdocs\getIt\protected\controllers\ClientesController.php(130): CActiveDataProvider->__construct('Clientes')
#9 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(50): ClientesController->actionIndex()
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#13 C:\xampp\htdocs\Yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Yii\framework\web\CController.php(283): CFilterChain->run()
#17 C:\xampp\htdocs\Yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(277): CController->run('index')
#19 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(136): CWebApplication->runController('clientes/index')
#20 C:\xampp\htdocs\Yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#21 C:\xampp\htdocs\getIt\index.php(13): CApplication->run()
#22 {main} REQUEST_URI=/getIt/index.php/clientes/index
2011/08/03 08:45:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'getit'@'189.187.202.158' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:364
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(313): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(291): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(372): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CApplication.php(429): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(609): CApplication->getDb()
#5 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(2275): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(372): CActiveRecordMetaData->__construct(Object(Clientes))
#7 C:\xampp\htdocs\Yii\framework\web\CActiveDataProvider.php(72): CActiveRecord::model('Clientes')
#8 C:\xampp\htdocs\getIt\protected\controllers\ClientesController.php(130): CActiveDataProvider->__construct('Clientes')
#9 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(50): ClientesController->actionIndex()
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#13 C:\xampp\htdocs\Yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Yii\framework\web\CController.php(283): CFilterChain->run()
#17 C:\xampp\htdocs\Yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(277): CController->run('index')
#19 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(136): CWebApplication->runController('clientes/index')
#20 C:\xampp\htdocs\Yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#21 C:\xampp\htdocs\getIt\index.php(13): CApplication->run()
#22 {main} REQUEST_URI=/getIt/index.php/clientes/index
2011/08/03 08:45:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'getit'@'189.187.202.158' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:364
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(313): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(291): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(372): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CApplication.php(429): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(609): CApplication->getDb()
#5 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(2275): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(372): CActiveRecordMetaData->__construct(Object(Clientes))
#7 C:\xampp\htdocs\Yii\framework\web\CActiveDataProvider.php(72): CActiveRecord::model('Clientes')
#8 C:\xampp\htdocs\getIt\protected\controllers\ClientesController.php(130): CActiveDataProvider->__construct('Clientes')
#9 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(50): ClientesController->actionIndex()
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#13 C:\xampp\htdocs\Yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Yii\framework\web\CController.php(283): CFilterChain->run()
#17 C:\xampp\htdocs\Yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(277): CController->run('index')
#19 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(136): CWebApplication->runController('clientes/index')
#20 C:\xampp\htdocs\Yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#21 C:\xampp\htdocs\getIt\index.php(13): CApplication->run()
#22 {main} REQUEST_URI=/getIt/index.php/clientes/index
2011/08/03 08:45:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'getit'@'189.187.202.158' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:364
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(313): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(291): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(372): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CApplication.php(429): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(609): CApplication->getDb()
#5 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(2275): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(372): CActiveRecordMetaData->__construct(Object(Clientes))
#7 C:\xampp\htdocs\Yii\framework\web\CActiveDataProvider.php(72): CActiveRecord::model('Clientes')
#8 C:\xampp\htdocs\getIt\protected\controllers\ClientesController.php(130): CActiveDataProvider->__construct('Clientes')
#9 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(50): ClientesController->actionIndex()
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#13 C:\xampp\htdocs\Yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Yii\framework\web\CController.php(283): CFilterChain->run()
#17 C:\xampp\htdocs\Yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(277): CController->run('index')
#19 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(136): CWebApplication->runController('clientes/index')
#20 C:\xampp\htdocs\Yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#21 C:\xampp\htdocs\getIt\index.php(13): CApplication->run()
#22 {main} REQUEST_URI=/getIt/index.php/clientes/index
2011/08/03 08:46:18 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'getit'@'189.187.202.158' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:364
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(313): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(291): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(372): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CApplication.php(429): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(609): CApplication->getDb()
#5 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(2275): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(372): CActiveRecordMetaData->__construct(Object(Clientes))
#7 C:\xampp\htdocs\Yii\framework\web\CActiveDataProvider.php(72): CActiveRecord::model('Clientes')
#8 C:\xampp\htdocs\getIt\protected\controllers\ClientesController.php(130): CActiveDataProvider->__construct('Clientes')
#9 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(50): ClientesController->actionIndex()
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#13 C:\xampp\htdocs\Yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Yii\framework\web\CController.php(283): CFilterChain->run()
#17 C:\xampp\htdocs\Yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(277): CController->run('index')
#19 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(136): CWebApplication->runController('clientes/index')
#20 C:\xampp\htdocs\Yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#21 C:\xampp\htdocs\getIt\index.php(13): CApplication->run()
#22 {main} REQUEST_URI=/getIt/index.php/clientes/index
